- parameters : bool
  visualize : true
  save_simulation_results : false
  save_model : false
  load_from_file : true
  load_parameters : false
- parameters : string
  save_simulation_results/filename : simulation_results.txt
  save_model/filename : 6dof_9musc.osim
  load_from_file/filename : ../src/opensim-model/models/6dof_9musc.osim
  load_parameters/filename : ../src/opensim-model/models/6dof_9musc_param.txt
