include ../../../mf/webots8-version.mf
include ../../../mf/webots-common-physics.mf

CFLAGS=-O2 -I../../../../../lib/  -std=gnu++0x  -static-libstdc++ -static-libgcc

include ../../../mf/webots-plugin.mf

